# Generated by Django 3.1.7 on 2021-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=150)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
